<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mahod.Intergreen.Core\Mahod.Intergreen.Core.csproj" />
    <ProjectReference Include="..\..\src\Mahod.Intergreen.Rules\Mahod.Intergreen.Rules.csproj" />
    <ProjectReference Include="..\..\src\Mahod.Intergreen.Excel\Mahod.Intergreen.Excel.csproj" />
    <ProjectReference Include="..\..\src\Mahod.Intergreen.Reporting\Mahod.Intergreen.Reporting.csproj" />
    <ProjectReference Include="..\..\src\Mahod.Intergreen.Geometry\Mahod.Intergreen.Geometry.csproj" />
  </ItemGroup>

</Project>
